### ISSUE TITLE
help

### ISSUE THREAD

**Issue by vectorez** [datauy/DondeReciclo-3B#75]
Hola buenas, me pueden dar una mano con el despliegue, 
![image](https://github.com/datauy/DondeReciclo-3B/assets/10076619/3cc909d9-a5e7-4eb0-b3d5-7a73a4d6d171)

**Comment by vectorez** [comment]
No logro conectar con la base de datos ni realizar la migración

**Comment by fernandouval** [comment]
Buenas @vectorez Ahí tendrías que crear tu base de datos de postgres y activar la extensión de postgis (asumiendo que tengas lo que precisás: https://postgis.net/documentation/getting_started/). Habría que cambiar el host a la IP o nombre (ej: localhost), y los datos de cconexión a la base creada. Luego podés generar la estructura de la base con el comando `rails db:migrate`

**Comment by vectorez** [comment]
![image](https://github.com/datauy/DondeReciclo-3B/assets/10076619/dce005ad-4b55-4307-bccc-a024b4c9d8b9)
la conexión con la base de datos se está realizando, tengo habilitado la extensión, pero no se realiza la migración  

![image](https://github.com/datauy/DondeReciclo-3B/assets/10076619/836f8eb9-663a-4547-af8c-3545c09461be)

**Comment by vectorez** [comment]
![image](https://github.com/datauy/DondeReciclo-3B/assets/10076619/06d3183e-aa1d-475d-bb8b-667ade16f61d)

**Comment by vectorez** [comment]
¿Realice una instalación limpia en DO y el comando migrar inicia la migración, pero tiene problemas, existe un branch más actualizado, o debo modificar algo? 

![image](https://github.com/datauy/DondeReciclo-3B/assets/10076619/37f127e7-cc2a-43a7-8114-ed9bed507cac)
